### ISSUE TITLE
WirelessPrinting v2

### ISSUE THREAD

**Issue by cpeuschel** [probonopd/WirelessPrinting#166]
I love this project, but we have some issues, so can we start a new project (from scratch) with new features? :) 

Here some ideas (based on some issues):
- HTTPS support
- Security
  - Enable OTA password (stored in SPIFF?)
  - API auth
- Beautiful Dashboard, maybe esp-dash :) ?
- WirelessPrinting settings site
  - Store password like API auth or OTA password
  - ESP Hostname 
  - maybe to store some custom commands like "emergency stop" or "abort print"
- File manager
- Camera support 
  - I'm using an external TP-Link Tapo camera, maybe It's possible to integrate the stream? In my opinion, the eps32 with camera is very useless because the quality isn't good
- Test integration like https://github.com/cpeuschel/streamdeck-octodeck or Home Assistant integration and mark as "feature"
-  etc.

Maybe some developers are here to help and get the WirelessPrinting on the next level :)

@probonopd: what do you think?

**Comment by probonopd** [comment]
For me WirelessPrinting is pretty much feature complete as it is. Since I only run it inside my trusted network, I don't need any security features.

If I had to do it from scratch, I would probably be looking into using the ESP32-S2 with USB host capabilities, because it is getting increasingly hard to find serial ports on 3D printers.
It looks like ESP32S2 is supported by https://github.com/espressif/arduino-esp32 nowadays, although I don't know the extent of USB host support for various USB-to-serial chips used in 3D printers.

If you need more advanced functionality it might be worthwhile to look into implementing something for the Raspberry Pi Zero W in Golang.
