### ISSUE TITLE
[Newbie] All accessories and connection

### ISSUE THREAD

**Issue by Dark-V** [probonopd/WirelessPrinting#179]
I don't find any references with my question in closed issues, so what i need to use this code for my 3D printer? 
So read readme i found two ways of setup. 
I just to want buy this all an once and don't have any exprience in this, so that's why i asking this.

First.
- WEMOS D1 
- Arduino sd card reader
- SD-card

Second 
- TTGO-T1
- SD-card

And that all what i need? What about any ISP (Bootloaders)?
And can someone attach a photo of 3D printer motherboard with working connection using WEMOS or TTGO?
Also be great, add this photos or any guide for newbie like me in readme or github wiki.

**Comment by probonopd** [comment]
You need an ESP board with attached SD card reader. There are many ways to do this but a WEMOS D1 + SD card shield or a TTGO-T1 are probably the easiest options.

You need to connect TX, RX, GND, +5V between your 3D printer motherboard and your ESP board. Since each 3D printer motherboard is different there cannot be one guide that fits all. 

Here is one example for a Creality board:
https://www.youtube.com/watch?v=QNxE_v5G_bg

Your board will most likely be different. Some even include pin headers for the serial pins.
