### ISSUE TITLE
[Question] About handlePrint function content

### ISSUE THREAD

**Issue by GMagician** [probonopd/WirelessPrinting#48]
Hi, sorry again to bother but I think I'm missing something in analyzing `handlePrint` function.

it seems that code is exacly the same when `hasSD` is true or false (only filename is different). In such case it would be more readable to don't create redundant code.

Please I don't want to hurt you with all such question about coding style but I'm analyzing your code to learn something about how you managed all this (I'm not so skilled in arduino programming) and I wan't to be ready to manage this by myself to use it in my printer...

**Comment by probonopd** [comment]
> it seems that code is exacly the same when hasSD is true or false (only filename is different). In such case it would be more readable to don't create redudant code.

Indeed - do you want to send a pull request?

During development, I ran into some very strange bugs that may have to do with timing and limited resources, so even if on paper something looks equivalent you may be surprised that it does not behave 100% the same, because the compiler does some optimizations as well.

So if you change it, please test it well to ensure that it does actually not break anything.

I am doing this in my spare time, and the code as it is now is working for me, so I don't touch it unless something is broken or a feature has to be added.

> I'm analyzing your code to learn something about how you managed all this

Mainly by trial and error.
