### ISSUE TITLE
Stops printing after ca. 26 minutes

### ISSUE THREAD

**Issue by probonopd** [probonopd/WirelessPrinting#9]
Had it stop printing after ca. 26 minutes. Is this because the HTTP request times out at some point? Would it be more stable if we did not send the printer <-> ESP8266 communication as a HTTP response while printing?

The last lines of communication:

```
#18785
--> G0 X33.645 Y38.171
<-- G0 X33.645 Y38.171
<-- ok
GOT OK

#18786
--> G0 F3000 X34.846 Y38.241
<-- G0 F3000 X34.846 Y38.241
<-- ok
GOT OK

#18787
--> G1 F6000 X37.363 Y40.757 E780.3733
<-- G1 F6000 X37.363 Y40.757 E780.3733
<-- ok
GOT OK

(Stalled here)

curl: (56) Recv failure: Connection timed out
```

The SP8266 then rebooted after an additional ca. 3-5 minutes.

Can this be reproduced?

**Comment by probonopd** [comment]
Let's see whether https://github.com/probonopd/WirelessPrinting/commit/cfde7b92c8cc7f5e229962216df229dc94045ddc addresses this.

**Comment by dentex** [comment]
Hello.
I'm having the same problem, so I'm writing here instead of opening a new issue.

I'm using a generic ESP32 board (probably known as "development board"; I'm not sure. It's just a Chinese board I got from Aliexpress 
https://s.click.aliexpress.com/e/cYl5MYek)

The print seems to stop after about 10~20 minutes.

Other things I found are also that:
- no progress is shown on the printer LCD
and
- the pre-built version doesn't seem to work on my ESP32. I built it myself with the Arduino IDE manually adding the various libraries needed.
